# Generated by Django 4.2.18 on 2025-01-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvmodel',
            old_name='csv_path',
            new_name='csv',
        ),
        migrations.RenameField(
            model_name='surrogatematricmodel',
            old_name='model_path',
            new_name='model',
        ),
    ]
