# Generated by Django 4.2.18 on 2025-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0004_remove_flowmodel_csv_flowmodel_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmodel',
            name='concat_csv',
            field=models.FileField(blank=True, null=True, upload_to='flows/'),
        ),
    ]
