# Generated by Django 4.2.18 on 2025-01-24 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0006_rename_columnmodel_concatcolumnmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50)),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='data_processing.csvmodel')),
            ],
        ),
    ]
