# Generated by Django 4.2.18 on 2025-01-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0007_columnmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concatcolumnmodel',
            name='missing_value_method',
        ),
    ]
