# Generated by Django 4.2.18 on 2025-01-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0008_remove_concatcolumnmodel_missing_value_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concatcolumnmodel',
            name='optimize_goal',
        ),
        migrations.AlterField(
            model_name='histogrammodel',
            name='column',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='histograms', to='data_processing.concatcolumnmodel'),
        ),
    ]
