# Generated by Django 4.2.18 on 2025-01-31 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0012_remove_searchresultmodel_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surrogatematricmodel',
            name='flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_matric', to='data_processing.flowmodel'),
        ),
    ]
