# Generated by Django 4.2.18 on 2025-01-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0013_alter_surrogatematricmodel_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surrogateresultmodel',
            name='ground_truth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='surrogateresultmodel',
            name='predicted',
            field=models.FloatField(),
        ),
    ]
