# Generated by Django 4.2.18 on 2025-01-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0014_alter_surrogateresultmodel_ground_truth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surrogatematricmodel',
            name='model',
        ),
    ]
