# Generated by Django 4.2.18 on 2025-01-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0015_remove_surrogatematricmodel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmodel',
            name='model',
            field=models.FileField(blank=True, default=None, null=True, upload_to='surrogate_model/'),
        ),
    ]
