# Generated by Django 4.2.18 on 2025-01-31 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0016_flowmodel_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurrogateFeatureImportanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_importance', models.FloatField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_feature_importance', to='data_processing.concatcolumnmodel')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_feature_importance', to='data_processing.flowmodel')),
            ],
        ),
    ]
