# Generated by Django 4.2.18 on 2025-01-31 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_processing",
            "0019_rename_optimizationmodel_controllableoptimizationmodel",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllableoptimizationmodel",
            name="optimize_goal",
            field=models.IntegerField(
                choices=[(1, "Maximize"), (2, "Minimize"), (3, "Fit_to_the_range")],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="OutputOptimizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optimize_goal",
                    models.IntegerField(
                        choices=[
                            (1, "Maximize"),
                            (2, "Minimize"),
                            (3, "Fit_to_the_range"),
                            (4, "Fit_to_the_properties"),
                        ],
                        default=1,
                    ),
                ),
                ("target_value", models.FloatField(default=0)),
                (
                    "column",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_optimizations",
                        to="data_processing.concatcolumnmodel",
                    ),
                ),
            ],
        ),
    ]
