# Generated by Django 4.2.18 on 2025-01-31 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_processing",
            "0020_alter_controllableoptimizationmodel_optimize_goal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllableoptimizationmodel",
            name="column",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controllable_optimizations",
                to="data_processing.concatcolumnmodel",
            ),
        ),
        migrations.AlterField(
            model_name="outputoptimizationmodel",
            name="optimize_goal",
            field=models.IntegerField(
                choices=[
                    (1, "Maximize"),
                    (2, "Minimize"),
                    (3, "Fit_to_the_properties"),
                ],
                default=1,
            ),
        ),
    ]
