# Generated by Django 4.2.18 on 2025-01-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50)),
                ('column_type', models.CharField(choices=[('numerical', 'Numerical'), ('categorical', 'Categorical'), ('unavailable', 'Unavailable')], default='unavailable', max_length=13)),
                ('property_type', models.CharField(choices=[('environmental', 'Environmental'), ('controllable', 'Controllable'), ('output', 'Output')], default='environmental', max_length=13)),
                ('missing_values_ratio', models.FloatField(default=0)),
                ('missing_value_method', models.IntegerField(choices=[(1, 'Drop'), (2, 'Mean'), (3, 'Median'), (4, 'Mode'), (5, 'Zero')], default=1)),
                ('optimize_goal', models.IntegerField(choices=[(1, 'Do_not_optimize'), (2, 'Maximize'), (3, 'Minimize'), (4, 'Fit_to_the_range'), (5, 'Fit_to_the_properties')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CsvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.FileField(upload_to='csv_files/')),
                ('writer', models.CharField(max_length=20)),
                ('size', models.FloatField(default=0)),
                ('rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(max_length=255)),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_model', to='data_processing.csvmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurrogateResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_truth', models.JSONField()),
                ('predicted', models.JSONField()),
                ('rank', models.IntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_result', to='data_processing.columnmodel')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_result', to='data_processing.flowmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SurrogateMatricModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_squared', models.FloatField()),
                ('rmse', models.FloatField()),
                ('model_path', models.FileField(upload_to='surrogate_model/')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_matric', to='data_processing.columnmodel')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_matric', to='data_processing.flowmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_truth', models.JSONField()),
                ('predicted', models.JSONField()),
                ('importance', models.FloatField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_result', to='data_processing.columnmodel')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_result', to='data_processing.flowmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HistogramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.JSONField()),
                ('bin_edges', models.JSONField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histogram_record', to='data_processing.columnmodel')),
            ],
        ),
        migrations.AddField(
            model_name='flowmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_model', to='data_processing.projectmodel'),
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CsvModel_files', to='data_processing.projectmodel'),
        ),
        migrations.AddField(
            model_name='columnmodel',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='data_processing.flowmodel'),
        ),
    ]
