# Generated by Django 4.2.18 on 2025-01-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistogramRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('counts', models.JSONField()),
                ('bin_edges', models.JSONField()),
                ('column_type', models.CharField(choices=[('numerical', 'Numerical'), ('categorical', 'Categorical')], default='numerical', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histograms', to='data_processing.csvdatarecord')),
            ],
        ),
    ]
