# Generated by Django 4.2.18 on 2025-01-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_rename_csv_path_csvmodel_csv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmodel',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_model', to='data_processing.csvmodel'),
        ),
    ]
