# Generated by Django 4.2.18 on 2025-01-17 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0003_csvdatarecord_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdatarecord',
            name='writer',
            field=models.CharField(default='관리자', max_length=20),
            preserve_default=False,
        ),
    ]
