# Generated by Django 4.2.18 on 2025-01-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0004_csvdatarecord_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(max_length=255)),
                ('csv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_model', to='data_processing.csvdatarecord')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_model', to='data_processing.project')),
            ],
        ),
    ]
