# Generated by Django 4.2.18 on 2025-01-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0005_flowmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdatarecord',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='flowmodel',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='flowmodel',
            name='csv_id',
        ),
        migrations.AddField(
            model_name='flowmodel',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_model', to='data_processing.csvdatarecord'),
        ),
    ]
