# Generated by Django 4.2.18 on 2025-01-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0006_rename_project_id_csvdatarecord_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columnrecord',
            old_name='csv_id',
            new_name='csv',
        ),
    ]
