# Generated by Django 4.2.18 on 2025-01-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0007_rename_csv_id_columnrecord_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowmodel',
            name='csv',
        ),
        migrations.CreateModel(
            name='FlowCsvDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_csv_data_record', to='data_processing.csvdatarecord')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_csv_data_record', to='data_processing.flowmodel')),
            ],
        ),
    ]
