# Generated by Django 4.2.18 on 2025-01-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0008_remove_flowmodel_csv_flowcsvdatarecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnrecord',
            name='is_unique',
        ),
    ]
