# Generated by Django 4.2.18 on 2025-01-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0009_remove_columnrecord_is_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdatarecord',
            name='data',
        ),
    ]
