# Generated by Django 4.2.18 on 2025-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0010_remove_csvdatarecord_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdatarecord',
            name='file_name',
        ),
        migrations.AddField(
            model_name='csvdatarecord',
            name='file',
            field=models.FileField(default=None, upload_to='csv_files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvdatarecord',
            name='rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvdatarecord',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
