# Generated by Django 4.2.18 on 2025-01-31 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0011_alter_optimizationmodel_optimize_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresultmodel',
            name='importance',
        ),
    ]
