# Generated by Django 4.2.18 on 2025-01-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0011_remove_csvdatarecord_file_name_csvdatarecord_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histogramrecord',
            old_name='column_id',
            new_name='column',
        ),
    ]
