# Generated by Django 4.2.18 on 2025-01-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0012_rename_column_id_histogramrecord_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnrecord',
            name='missing_values_ratio',
            field=models.FloatField(default=0),
        ),
    ]
