# Generated by Django 4.2.18 on 2025-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0013_columnrecord_missing_values_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnrecord',
            name='missing_value_method',
            field=models.CharField(choices=[('drop', 'Drop'), ('mean', 'Mean'), ('median', 'Median'), ('mode', 'Mode'), ('zero', 'Zero')], default='drop', max_length=6),
        ),
    ]
