# Generated by Django 4.2.18 on 2025-01-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0014_columnrecord_missing_value_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnrecord',
            name='optimize_goal',
            field=models.CharField(choices=[('do_not_optimize', 'Do not optimize'), ('maximize', 'Maximize'), ('minimize', 'Minimize'), ('fit_to_the_range', 'Fit to the range'), ('fit_to_the_properties', 'Fit to the properties')], default='do_not_optimize', max_length=21),
        ),
    ]
