# Generated by Django 4.2.18 on 2025-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0015_columnrecord_optimize_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnrecord',
            name='column_type',
            field=models.IntegerField(choices=[(1, 'Numerical'), (2, 'Categorical'), (3, 'Unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='columnrecord',
            name='missing_value_method',
            field=models.IntegerField(choices=[(1, 'Drop'), (2, 'Mean'), (3, 'Median'), (4, 'Mode'), (5, 'Zero')], default=1),
        ),
        migrations.AlterField(
            model_name='columnrecord',
            name='optimize_goal',
            field=models.IntegerField(choices=[(1, 'Do not optimize'), (2, 'Maximize'), (3, 'Minimize'), (4, 'Fit to the range'), (5, 'Fit to the properties')], default=1),
        ),
        migrations.AlterField(
            model_name='columnrecord',
            name='property_type',
            field=models.IntegerField(choices=[(1, 'Environmental'), (2, 'Controllable'), (3, 'Output')], default=1),
        ),
    ]
