# Generated by Django 4.2.18 on 2025-01-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0018_featureimportancemodel_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OptimizationModel",
            new_name="ControllableOptimizationModel",
        ),
    ]
