# Generated by Django 4.2.18 on 2025-02-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0021_alter_controllableoptimizationmodel_column_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outputoptimizationmodel",
            old_name="target_value",
            new_name="maximum_value",
        ),
        migrations.AddField(
            model_name="outputoptimizationmodel",
            name="minimum_value",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="controllableoptimizationmodel",
            name="optimize_goal",
            field=models.IntegerField(
                choices=[
                    (1, "no optimization"),
                    (2, "Maximize"),
                    (3, "Minimize"),
                    (4, "Fit_to_the_range"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="outputoptimizationmodel",
            name="optimize_goal",
            field=models.IntegerField(
                choices=[
                    (1, "Maximize"),
                    (2, "Minimize"),
                    (3, "Fit_to_the_range"),
                    (4, "Fit_to_the_properties"),
                ],
                default=1,
            ),
        ),
    ]
