# Generated by Django 4.2.18 on 2025-02-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0023_optimizationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationmodel',
            name='optimize_order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
