# Generated by Django 4.2.18 on 2025-02-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0024_optimizationmodel_optimize_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concatcolumnmodel',
            name='column_type',
            field=models.CharField(choices=[('numerical', 'Numerical'), ('categorical', 'Categorical'), ('text', 'Text'), ('unavailable', 'Unavailable')], default='unavailable', max_length=13),
        ),
    ]
