# Generated by Django 4.2.18 on 2025-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0025_alter_concatcolumnmodel_column_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowmodel",
            name="processing_csv",
            field=models.FileField(
                blank=True, null=True, upload_to="flows/processing_csv"
            ),
        ),
        migrations.AlterField(
            model_name="flowmodel",
            name="concat_csv",
            field=models.FileField(
                blank=True, null=True, upload_to="flows/concat_csv/"
            ),
        ),
    ]
