# Generated by Django 4.2.18 on 2025-02-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0026_flowmodel_processing_csv_alter_flowmodel_concat_csv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowmodel",
            name="processing_csv",
        ),
        migrations.AddField(
            model_name="flowmodel",
            name="preprocessed_csv",
            field=models.FileField(
                blank=True, null=True, upload_to="flows/preprocessed_csv"
            ),
        ),
    ]
