# Generated by Django 4.2.18 on 2025-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0028_remove_flowmodel_preprocessed_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowmodel",
            name="preprocessed_csv",
            field=models.FileField(
                blank=True, null=True, upload_to="flows/preprocessed_csv"
            ),
        ),
    ]
