# Generated by Django 4.2.18 on 2025-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0029_flowmodel_preprocessed_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowmodel",
            name="progress",
            field=models.CharField(
                blank=True, default="Start", max_length=255, null=True
            ),
        ),
    ]
