# Generated by Django 4.2.18 on 2025-02-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_processing",
            "0031_surrogatematricmodel_mse_alter_csvmodel_csv_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="surrogatematricmodel",
            old_name="mse",
            new_name="mae",
        ),
    ]
