# Generated by Django 4.2.18 on 2025-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0033_alter_optimizationmodel_maximum_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmodel',
            name='progress',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
