# Generated by Django 4.2.18 on 2025-02-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0034_alter_flowmodel_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultmodel',
            name='average_change_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
