# Generated by Django 4.2.18 on 2025-02-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0035_searchresultmodel_average_change_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surrogateresultmodel',
            name='ground_truth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='surrogateresultmodel',
            name='predicted',
            field=models.CharField(max_length=255),
        ),
    ]
