# Generated by Django 4.2.18 on 2025-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0036_alter_surrogateresultmodel_ground_truth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surrogatematricmodel',
            name='mae',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surrogatematricmodel',
            name='rmse',
            field=models.FloatField(default=0, null=True),
        ),
    ]
